const YT_API_KEY = "AIzaSyCY_qSAYwmCxSE5LyJbH6j7c6VqnOMVNNg";

export const YOUTUBE_VIDEOS_API =
  "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&maxResults=52&regionCode=IN&key=" +
  YT_API_KEY;

export const YOUTUBE_SEARCH_API =
  "http://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q=";

const youtubeVideosList = {
  kind: "youtube#videoListResponse",
  etag: "UqY_rJ5Ic-Y1Z0CyayLTmohZcic",
  items: [
    {
      kind: "youtube#video",
      etag: "aihSyjYXTIYB_gvZalL2AMwJx0I",
      id: "aP7kVq5bewo",
      snippet: {
        publishedAt: "2024-03-12T02:52:18Z",
        channelId: "UC7_YxT-KID8kRbqZo7MyscQ",
        title: "I'm tired",
        description:
          "I'm tired. Here's why and some other ramblings.\nRambling with Bob and Wade ► https://open.spotify.com/show/2X40qLyoj1wQ2qE5FVpA7x\nRambling with Tyler ► https://open.spotify.com/show/4Hn3qhWe5NqnhLFKytyfFW",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/aP7kVq5bewo/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/aP7kVq5bewo/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/aP7kVq5bewo/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/aP7kVq5bewo/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/aP7kVq5bewo/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Markiplier",
        tags: ["markiplier", "im tired"],
        categoryId: "20",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "I'm tired",
          description:
            "I'm tired. Here's why and some other ramblings.\nRambling with Bob and Wade ► https://open.spotify.com/show/2X40qLyoj1wQ2qE5FVpA7x\nRambling with Tyler ► https://open.spotify.com/show/4Hn3qhWe5NqnhLFKytyfFW",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT6M55S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4314725",
        likeCount: "461874",
        favoriteCount: "0",
        commentCount: "31382",
      },
    },
    {
      kind: "youtube#video",
      etag: "yf_7dtpmCcTOyK_Bh7K7vJLXyxA",
      id: "VhWqpvGq6b4",
      snippet: {
        publishedAt: "2024-03-11T01:49:46Z",
        channelId: "UC_IpSl6O_-IRAA6fiNs05Gg",
        title:
          "Ryan Gosling and Mark Ronson Perform 'I'm Just Ken' at Oscars 2024",
        description:
          "Ryan Gosling and Mark Ronson perform the Oscar nominated original song 'I'm Just Ken' from BARBIE at Oscars 2024. See more performances and highlights at Oscars.com and in the ABC app!\n\nSubscribe: http://goo.gl/mo7HqT",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/VhWqpvGq6b4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/VhWqpvGq6b4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/VhWqpvGq6b4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/VhWqpvGq6b4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/VhWqpvGq6b4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "ABC",
        tags: [
          "achievement",
          "glamour",
          "glitz",
          "highlights",
          "prestige",
          "stars",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Ryan Gosling and Mark Ronson Perform 'I'm Just Ken' at Oscars 2024",
          description:
            "Ryan Gosling and Mark Ronson perform the Oscar nominated original song 'I'm Just Ken' from BARBIE at Oscars 2024. See more performances and highlights at Oscars.com and in the ABC app!\n\nSubscribe: http://goo.gl/mo7HqT",
        },
      },
      contentDetails: {
        duration: "PT3M35S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        regionRestriction: {
          allowed: ["US"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "3474154",
        likeCount: "78843",
        favoriteCount: "0",
        commentCount: "3985",
      },
    },
    {
      kind: "youtube#video",
      etag: "qiuq3q5avYmW60NtkXEQM2Fl6wA",
      id: "oep7Pqj45IY",
      snippet: {
        publishedAt: "2024-03-12T16:00:38Z",
        channelId: "UCOuwU6aYcIgpKDdbekbUS2Q",
        title: "How To Be Cool",
        description:
          "How To Be Cool\n\nhttps://chainsclub.shop/\n\nMarks gonna ban me from the gram after this one",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/oep7Pqj45IY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/oep7Pqj45IY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/oep7Pqj45IY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/oep7Pqj45IY/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/oep7Pqj45IY/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "ChainsFR",
        tags: [
          "How To Be Cool",
          "become cool",
          "how to be cooler",
          "how to be cool in school",
          "how to get cool",
          "being cool",
          "cool in school",
          "cool tips",
          "chainsfr",
          "chains fr",
          "chainsfre",
          "chainsfr face reveal",
          "vaping be like",
          "elementary school in a nutshell",
          "chains for real",
          "chains",
          "chainz",
          "chains fo real",
          "chains for real high school",
          "middle school in a nutshell",
          "highschool in a nutshell",
          "middle school be like",
          "highschool be like",
          "school be like",
          "tips how to be cool",
          "xozero",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "How To Be Cool",
          description:
            "How To Be Cool\n\nhttps://chainsclub.shop/\n\nMarks gonna ban me from the gram after this one",
        },
      },
      contentDetails: {
        duration: "PT8M6S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "767365",
        likeCount: "58219",
        favoriteCount: "0",
        commentCount: "3850",
      },
    },
    {
      kind: "youtube#video",
      etag: "5Fo72oqM-h2mZk0BpNMUf-qfX3Y",
      id: "q9J0Ieu1xU8",
      snippet: {
        publishedAt: "2024-03-12T10:00:17Z",
        channelId: "UCtCiO5t2voB14CmZKTkIzPQ",
        title:
          "트와이스(TWICE)의 킬링보이스를 라이브로!ㅣOOH-AHH하게, CHEER UP, TT, KNOCK KNOCK, Heart shaker, YES or YES, ONE SPARK",
        description:
          "둘 중에 하나만 골라 트와이스 킬보 or 킬링보이스 😙🧡\n\n0:00 입장\n0:33 OOH-AHH하게\n02:08 CHEER UP\n03:28 TT\n04:58 KNOCK KNOCK\n06:11 LIKEY\n06:56 Heart shaker\n07:45 What is love?\n10:02 거북이\n11:15 SIGNAL\n12:56 Dance the Night away\n14:17 YES or YES\n15:23 Feel special\n17:29 The Feels\n18:53 Alcohol-free\n20:21 MOONLIGHT SUNRISE\n21:47 FANCY\n23:15 I GOT YOU\n25:31 ONE SPARK 🆕\n28:37 CANDY\n\n▶딩고뮤직 (Dingo Music) : http://bit.ly/Dingo__Music\n▶딩고프리스타일 (Dingo Freestyle) : http://bit.ly/Dingo__Freestyle\n▶일소라 (일반인들의 소름돋는 라이브) : http://bit.ly/ilsora\n\ncontact : musicbiz@makeus.com\n\n#TWICE #트와이스 #킬링보이스 \n#딩고뮤직 #KILLINGVOICE #DingoMusic",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/q9J0Ieu1xU8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/q9J0Ieu1xU8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/q9J0Ieu1xU8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/q9J0Ieu1xU8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/q9J0Ieu1xU8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "딩고 뮤직 / dingo music",
        tags: [
          "딩고뮤직",
          "dingo",
          "dingomusic",
          "music",
          "kpop",
          "live",
          "멜론",
          "세로라이브",
          "최신가요",
          "top100",
          "아이돌",
          "라이브",
          "음악",
          "딩고",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "트와이스(TWICE)의 킬링보이스를 라이브로!ㅣOOH-AHH하게, CHEER UP, TT, KNOCK KNOCK, Heart shaker, YES or YES, ONE SPARK",
          description:
            "둘 중에 하나만 골라 트와이스 킬보 or 킬링보이스 😙🧡\n\n0:00 입장\n0:33 OOH-AHH하게\n02:08 CHEER UP\n03:28 TT\n04:58 KNOCK KNOCK\n06:11 LIKEY\n06:56 Heart shaker\n07:45 What is love?\n10:02 거북이\n11:15 SIGNAL\n12:56 Dance the Night away\n14:17 YES or YES\n15:23 Feel special\n17:29 The Feels\n18:53 Alcohol-free\n20:21 MOONLIGHT SUNRISE\n21:47 FANCY\n23:15 I GOT YOU\n25:31 ONE SPARK 🆕\n28:37 CANDY\n\n▶딩고뮤직 (Dingo Music) : http://bit.ly/Dingo__Music\n▶딩고프리스타일 (Dingo Freestyle) : http://bit.ly/Dingo__Freestyle\n▶일소라 (일반인들의 소름돋는 라이브) : http://bit.ly/ilsora\n\ncontact : musicbiz@makeus.com\n\n#TWICE #트와이스 #킬링보이스 \n#딩고뮤직 #KILLINGVOICE #DingoMusic",
        },
        defaultAudioLanguage: "ko",
      },
      contentDetails: {
        duration: "PT31M33S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2206802",
        likeCount: "252875",
        favoriteCount: "0",
        commentCount: "19406",
      },
    },
    {
      kind: "youtube#video",
      etag: "Ll9b78yV6Ilp--yPyPSkuUYEPSI",
      id: "Q1LY7dBHEws",
      snippet: {
        publishedAt: "2024-03-11T14:24:48Z",
        channelId: "UCe0DNp0mKMqrYVaTundyr9w",
        title: "The Lore of Elden Ring is Cursed",
        description:
          "►Preorder Enotria: The Last Song - https://enotriathelastsong.com/preorder\n►Learn more about Enotria: The Last Song at @enotriathelastsong \nSHOUTOUTS:\n►@mispap1  & @VLimit11  for their footage, editing, and directing assistance. Mispap handled the footage and edit for ch.1-4, and V-limit handled the edit for chapters 5 and 6. Also very thankful to V-Limit for reviewing the script. Subscribe to them!\n►Cleverraptor for their \"Bloodstarved Spear\" mod https://www.nexusmods.com/eldenring/mods/4344\n►@SekiroDubi for their St. Trina discoveries\n►M4x2o for their closed captioning work on this video\n\n\nTIMESTAMPS ▼▼▼\n00:00 The DLC starts here...\n00:25 I: Omen\n07:48 II: The Formless Mother\n22:06 III: Mohgwyn Dyansty\n27:55 IV: Knights of the New Dynasty\n46:56 V: Miquella's Nightmare\n57:35 VI: A Bloody Bedchamber\n\nPATRONAGE\n►Become a patron for early access, exclusive merch, and more http://www.patreon.com/vaatividya\n\nMERCHANDISE\n►Consider buying a Displate poster here: https://bit.ly/43Ujbk1\n►Buy more Posters & Apparel at https://vaatividya.com/\n\n\nSPECIAL THANKS TO\n►Mispap1, for Lore / Prepare to Cry editing and footage -  @mispap1\n►Frans Bouma, for your legendary Elden Ring camera tools - https://fransbouma.com/\n►Rainer, for their modding assistance in these videos -  @rainergeis4071\n\nPLAYLISTS\n►My Best Videos: http://bit.ly/2oMp66a\n►Elden Ring Prepare to Cry: https://bit.ly/3ApeG2N\n►Elden Ring Lore: https://bit.ly/3q3saNf\n►Elden Ring Secrets: https://bit.ly/3RdCNbQ\n►Elden Ring News: https://bit.ly/2ZkDV2d\n►Sekiro Lore: https://bit.ly/2KGEzD1\n►Sekiro Secrets: https://bit.ly/2IsObhW\n►Dark Souls 3 Lore: http://bit.ly/2n0bU13\n►Dark Souls 3 News: http://bit.ly/1NQbgbW\n►Bloodborne Lore: http://bit.ly/1X9doOQ\n►Demon's Souls Lore: http://bit.ly/16mIF86\n►Dark Souls Remastered Lore: http://bit.ly/13x6nNs\n►Dark Souls 2 Lore: http://bit.ly/1dedWjI\n►Souls-like: http://bit.ly/1xCPDnu\n\n\nSOCIAL\n►Follow me on Twitter: https://twitter.com/VaatiVidya\n►Follow me on TikTok: https://www.tiktok.com/@vaatividya\n►Follow me on Twitch.tv: http://www.twitch.tv/vaatividya\n►Follow me on Tumblr: http://vaatividya.tumblr.com/\n►Follow me on Facebook: https://www.facebook.com/Vaatividya\n►Follow me on Patreon: http://www.patreon.com/vaatividya\n►Join me on Discord: http://discord.gg/vaatividya\n\n\nTHUMBNAIL ART\n►John Devlin\n\n\nMUSIC (most is royalty-free or licensed from Epidemic Sound. Sign up or browse here: (https://www.epidemicsound.com/referral/j49549/)\n►Close to Touch\n► Love You to D**th - Ruiqi Zhao\n►Grosvenor Manor, Alex Roe\n►Sage Oursler\n►ES_Questions - Rannar Sillard\n►ES_A Subtle Mind - Dream Cave\n►Steady Tension - Farrell Wooten\n►No Redemption - Christoffer Moe Ditlevsen\n►Lights Disappear - Christian Andersen\n►Birth of a Knight - Max Anson\n►Fire on the Bridge - Max Anson\n►Gargoyle - Eden Avery\n►Eyes Watching - Eden Avery.\n► End Of A Vicious Struggle\n►Gravity Fields - Hampus Naeselius\n►Eyes Watching - Eden Avery\n►Invisible Ink - Eden Avery\n►Portal Latrop - DEX 1200\n►Rise From the Shadows - Hampus Naeselius\n►Unshaken Loyalty - Sage Oursler\n►Tough Test - Christian Andersen\n►Gravity Fields - Hampus Naeselius \n\n\nPATRONS\n►I'd like to give sincere thanks to all my patrons - your contributions have changed the course of my life, allowing me to put more emphasis on video production in the future.\n\n\n►Special thanks to Soul of Cinder-tier Patrons: John, Mihaf, Matthew, Colin, budhawillyboy, Chattan, Aritz, Erlend, Michael, Finbarwrong, David, AmazinShawn, Aidan, Joshua, Ryan, Cat, Lucian, Nicholas, HugDucks, Kyle, Xavier, Justin, Andreas, Ian, Xensvet, Mike, Loak, Morningstar, Morgan, Vanguard, Ricakardsson, Seleiful, Dain, Diablo, Chase, Andronikos, Nezzly, Rune, Thomas, Jacob, One Unimpressed Boi, Matthew, Aj, GoldenSunX, Yousif, sean, Croonz, ndr.alng, Meistermuall, Armand, Albert, Liam, AJ, Aishlinn, Reiftyr, nicolas, and Ricky.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/Q1LY7dBHEws/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/Q1LY7dBHEws/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/Q1LY7dBHEws/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/Q1LY7dBHEws/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/Q1LY7dBHEws/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "VaatiVidya",
        tags: [
          "guide",
          "walkthrough",
          "lore",
          "dark",
          "souls",
          "dlc",
          "two",
          "bloodborne",
          "story",
          "vaatividya",
          "vaati",
          "vidya",
          "videos",
          "(video",
          "game)",
          "shadows",
          "twice",
          "from",
          "software",
          "sekiro",
          "combat",
          "tips",
          "tricks",
          "elden",
          "ring",
          "trailer",
          "demon's souls",
          "remake",
          "ps5",
          "playstation 5",
          "queen marika",
          "demigods",
          "great runes",
          "radagon",
          "mohg",
          "morgott",
          "radahn",
          "malenia",
          "miquella",
          "melina",
          "dragons",
          "prepare to cry",
          "secrets",
          "armored core 6",
          "vi",
          "all endings",
          "best build",
          "shadow of the erdtree",
          "SotE",
          "fires of rubicon",
          "bloodflame",
          "mother of truth",
          "formless mother",
          "varre",
          "st. trina",
        ],
        categoryId: "20",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "The Lore of Elden Ring is Cursed",
          description:
            "►Preorder Enotria: The Last Song - https://enotriathelastsong.com/preorder\n►Learn more about Enotria: The Last Song at @enotriathelastsong \nSHOUTOUTS:\n►@mispap1  & @VLimit11  for their footage, editing, and directing assistance. Mispap handled the footage and edit for ch.1-4, and V-limit handled the edit for chapters 5 and 6. Also very thankful to V-Limit for reviewing the script. Subscribe to them!\n►Cleverraptor for their \"Bloodstarved Spear\" mod https://www.nexusmods.com/eldenring/mods/4344\n►@SekiroDubi for their St. Trina discoveries\n►M4x2o for their closed captioning work on this video\n\n\nTIMESTAMPS ▼▼▼\n00:00 The DLC starts here...\n00:25 I: Omen\n07:48 II: The Formless Mother\n22:06 III: Mohgwyn Dyansty\n27:55 IV: Knights of the New Dynasty\n46:56 V: Miquella's Nightmare\n57:35 VI: A Bloody Bedchamber\n\nPATRONAGE\n►Become a patron for early access, exclusive merch, and more http://www.patreon.com/vaatividya\n\nMERCHANDISE\n►Consider buying a Displate poster here: https://bit.ly/43Ujbk1\n►Buy more Posters & Apparel at https://vaatividya.com/\n\n\nSPECIAL THANKS TO\n►Mispap1, for Lore / Prepare to Cry editing and footage -  @mispap1\n►Frans Bouma, for your legendary Elden Ring camera tools - https://fransbouma.com/\n►Rainer, for their modding assistance in these videos -  @rainergeis4071\n\nPLAYLISTS\n►My Best Videos: http://bit.ly/2oMp66a\n►Elden Ring Prepare to Cry: https://bit.ly/3ApeG2N\n►Elden Ring Lore: https://bit.ly/3q3saNf\n►Elden Ring Secrets: https://bit.ly/3RdCNbQ\n►Elden Ring News: https://bit.ly/2ZkDV2d\n►Sekiro Lore: https://bit.ly/2KGEzD1\n►Sekiro Secrets: https://bit.ly/2IsObhW\n►Dark Souls 3 Lore: http://bit.ly/2n0bU13\n►Dark Souls 3 News: http://bit.ly/1NQbgbW\n►Bloodborne Lore: http://bit.ly/1X9doOQ\n►Demon's Souls Lore: http://bit.ly/16mIF86\n►Dark Souls Remastered Lore: http://bit.ly/13x6nNs\n►Dark Souls 2 Lore: http://bit.ly/1dedWjI\n►Souls-like: http://bit.ly/1xCPDnu\n\n\nSOCIAL\n►Follow me on Twitter: https://twitter.com/VaatiVidya\n►Follow me on TikTok: https://www.tiktok.com/@vaatividya\n►Follow me on Twitch.tv: http://www.twitch.tv/vaatividya\n►Follow me on Tumblr: http://vaatividya.tumblr.com/\n►Follow me on Facebook: https://www.facebook.com/Vaatividya\n►Follow me on Patreon: http://www.patreon.com/vaatividya\n►Join me on Discord: http://discord.gg/vaatividya\n\n\nTHUMBNAIL ART\n►John Devlin\n\n\nMUSIC (most is royalty-free or licensed from Epidemic Sound. Sign up or browse here: (https://www.epidemicsound.com/referral/j49549/)\n►Close to Touch\n► Love You to D**th - Ruiqi Zhao\n►Grosvenor Manor, Alex Roe\n►Sage Oursler\n►ES_Questions - Rannar Sillard\n►ES_A Subtle Mind - Dream Cave\n►Steady Tension - Farrell Wooten\n►No Redemption - Christoffer Moe Ditlevsen\n►Lights Disappear - Christian Andersen\n►Birth of a Knight - Max Anson\n►Fire on the Bridge - Max Anson\n►Gargoyle - Eden Avery\n►Eyes Watching - Eden Avery.\n► End Of A Vicious Struggle\n►Gravity Fields - Hampus Naeselius\n►Eyes Watching - Eden Avery\n►Invisible Ink - Eden Avery\n►Portal Latrop - DEX 1200\n►Rise From the Shadows - Hampus Naeselius\n►Unshaken Loyalty - Sage Oursler\n►Tough Test - Christian Andersen\n►Gravity Fields - Hampus Naeselius \n\n\nPATRONS\n►I'd like to give sincere thanks to all my patrons - your contributions have changed the course of my life, allowing me to put more emphasis on video production in the future.\n\n\n►Special thanks to Soul of Cinder-tier Patrons: John, Mihaf, Matthew, Colin, budhawillyboy, Chattan, Aritz, Erlend, Michael, Finbarwrong, David, AmazinShawn, Aidan, Joshua, Ryan, Cat, Lucian, Nicholas, HugDucks, Kyle, Xavier, Justin, Andreas, Ian, Xensvet, Mike, Loak, Morningstar, Morgan, Vanguard, Ricakardsson, Seleiful, Dain, Diablo, Chase, Andronikos, Nezzly, Rune, Thomas, Jacob, One Unimpressed Boi, Matthew, Aj, GoldenSunX, Yousif, sean, Croonz, ndr.alng, Meistermuall, Armand, Albert, Liam, AJ, Aishlinn, Reiftyr, nicolas, and Ricky.",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT1H10M50S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1111684",
        likeCount: "51202",
        favoriteCount: "0",
        commentCount: "2672",
      },
    },
  ],
  nextPageToken: "CAUQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 5,
  },
};
export const LIVE_CHAT_COUNT = 25;

//live chat >>> infiniteScroll >>> pagination
